# Based on: https://docs.docker.com/guides/angular/deploy/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-list-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-list-frontend
  template:
    metadata:
      labels:
        app: shopping-list-frontend
    spec:
      containers:
        - name: shopping-list-frontend-containers
          image: akali013/shopping-list-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-list-frontend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: shopping-list-frontend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001